// 预加载脚本：通过 contextBridge 暴露安全的 API
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('echos', {
  getState: () => ipcRenderer.invoke('get-state'),
  start: () => ipcRenderer.invoke('start'),
  stop: () => ipcRenderer.invoke('stop'),
  restart: () => ipcRenderer.invoke('restart'),
  setSystemProxy: (enabled) => ipcRenderer.invoke('set-system-proxy', enabled),
  getSystemProxySummary: () => ipcRenderer.invoke('get-system-proxy-summary'),
  setRouteMode: (mode) => ipcRenderer.invoke('set-route-mode', mode),
  addServer: () => ipcRenderer.invoke('add-server'),
  renameServer: (id, name) => ipcRenderer.invoke('rename-server', id, name),
  saveServer: (server) => ipcRenderer.invoke('save-server', server),
  deleteServer: (id) => ipcRenderer.invoke('delete-server', id),
  selectServer: (id) => ipcRenderer.invoke('select-server', id),
  importServers: (list) => ipcRenderer.invoke('import-servers', list),
  exportServers: () => ipcRenderer.invoke('export-servers'),
  importFromFile: () => ipcRenderer.invoke('import-from-file'),
  clearLogs: () => ipcRenderer.invoke('clear-logs'),
  setAutoLaunch: (enabled) => ipcRenderer.invoke('set-auto-launch', enabled),
  setConfig: (patch) => ipcRenderer.invoke('set-config', patch),
  checkUpdates: () => ipcRenderer.invoke('check-updates'),
  selfCheck: () => ipcRenderer.invoke('self-check'),
  revealLogs: () => ipcRenderer.invoke('reveal-logs'),
  openUpdateUrl: (url) => ipcRenderer.invoke('open-update-url', url),
  subscribeKernelLogs: (on) => ipcRenderer.invoke('subscribe-kernel-logs', on),
  // 端口占用
  findPortOccupant: (port) => ipcRenderer.invoke('find-port-occupant', port),
  killProcess: (pid) => ipcRenderer.invoke('kill-process', pid),
  portDecision: (decision) => ipcRenderer.invoke('port-decision', decision),
  pickFreePort: () => ipcRenderer.invoke('pick-free-port'),
  testNodes: () => ipcRenderer.invoke('test-nodes'),
  testHosts: (hosts) => ipcRenderer.invoke('test-hosts', hosts),
  fetchCfNodes: (apiUrls) => ipcRenderer.invoke('fetch-cf-nodes', apiUrls),
  // 订阅器
  fetchSubscription: (url) => ipcRenderer.invoke('fetch-subscription', url),
  importSubscription: (nodes) => ipcRenderer.invoke('import-subscription', nodes),
  updateSubscription: (url) => ipcRenderer.invoke('update-subscription', url),
  // WebDAV / 备份
  getWebdav: () => ipcRenderer.invoke('get-webdav'),
  saveWebdav: (raw) => ipcRenderer.invoke('save-webdav', raw),
  removeWebdav: () => ipcRenderer.invoke('remove-webdav'),
  backupWebdav: () => ipcRenderer.invoke('backup-webdav'),
  restoreWebdav: () => ipcRenderer.invoke('restore-webdav'),
  deleteWebdavBackup: () => ipcRenderer.invoke('delete-webdav-backup'),
  backupLocal: () => ipcRenderer.invoke('backup-local'),
  restoreLocal: () => ipcRenderer.invoke('restore-local'),
  getFailureHint: () => ipcRenderer.invoke('get-failure-hint'),
  onState: (cb) => ipcRenderer.on('state', (_e, s) => cb(s)),
  onLogLine: (cb) => ipcRenderer.on('log-line', (_e, l) => cb(l)),
  onKernelLog: (cb) => ipcRenderer.on('kernel-log', (_e, l) => cb(l)),
  onUpdateAvailable: (cb) => ipcRenderer.on('update-available', (_e, r) => cb(r)),
  onPortConflict: (cb) => ipcRenderer.on('port-conflict', (_e, r) => cb(r)),
  onStartFailed: (cb) => ipcRenderer.on('start-failed', (_e, r) => cb(r)),
  onCheckLine: (cb) => ipcRenderer.on('check-line', (_e, l) => cb(l)),
  onToastMsg: (cb) => ipcRenderer.on('toast-msg', (_e, r) => cb(r))
});